# Site Bilgileri
title: "Elektrik Depo Blog"
description: "Elektrik, elektronik ve teknoloji dünyasından haberler, incelemeler ve rehberler"
baseurl: "/elektrikdepo"
url: "https://perspektif-teknoloji.github.io"

# Build Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Permalink
permalink: /:categories/:title/

# Site Ayarları
timezone: Europe/Istanbul
lang: tr
locale: tr_TR

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md